name: Code Quality checks
on:
  pull_request:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:

  prettier:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Dump GitHub context
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install -D

      - name: Prettify code
        id: prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_plugins: "prettier-plugin-apex @prettier/plugin-xml"
          prettier_options: --check **/*.{js,md,html,css,cls}
          only_changed: True
          dry: True

      # - name: Test Prettier command CHECK
      #   run: npm run prettier:verify

      - name:  Test Prettier command WRITE
        if: failure()
        run: npm run prettier && git status

      - name:  Test Prettier command WRITE
        if: success()
        run: echo "Prettier check passed"

      # - name: Conidtionally commit changes
      #   if: 

      # commiit changes 