name: Code Quality checks
on:
  pull_request:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:

  prettier:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install

      # - name: Prettify code
      #   uses: creyD/prettier_action@v4.3
      #   with:
      #     prettier_plugins: "prettier-plugin-apex @prettier/plugin-xml"
      #     prettier_options: --check **/*.{js,md,html,css}
      #     only_changed: True
      #     dry: True

  # prettier:
  #   name: Prettier
  #   runs-on: ubuntu-22.04
  #   strategy:
  #     matrix:
  #       node-version: [18]
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         ref: ${{ github.head_ref }}
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         # cache: "pnpm"
  #     - name: Install dependencies
  #       # run: pnpm install -D
  #       run: npm install
      - name: Test Prettier command
        # run: pnpm prettier:check
        run: npm run prettier