name: Code Quality checks
on:
  pull_request:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:

  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # prettier_options: --write **/*.{js,md}
          prettier_options: --check
          prettier_plugins: "prettier-plugin-apex"
          only_changed: True
          dry: True

  # prettier:
  #   name: Prettier
  #   runs-on: ubuntu-22.04
  #   strategy:
  #     matrix:
  #       node-version: [18]
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         ref: ${{ github.head_ref }}
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #         # cache: "pnpm"
  #     - name: Install dependencies
  #       # run: pnpm install -D
  #       run: npm install
  #     - name: Check formatting with Prettier
  #       # run: pnpm prettier:check
  #       run: npm run prettier:verify